config/routes.rb
MarketAid::Application.routes.draw do

  resources :oauth_consumers do
    member do
      get :callback
      get :callback2
      match 'client/*endpoint' => 'oauth_consumers#client'
    end
  end

  match "dashboard" => "dashboard#index", :as => :dashboard
  match "feed" => "feed#index", :as => :feed
  match "analytics" => "analytics#index", :as => :analytics
  match "schedule" => "schedule#index", :as => :schedule
  match "schedule/schedule_meetup_event" => "schedule#schedule_meetup_event", :via => [:put,:post]
  match "schedule/schedule_meetup_comment" => "schedule#schedule_meetup_comment", :via => [:put,:post]
  match "schedule/schedule_tweet" => "schedule#schedule_tweet", :via => [:put,:post]
  match "schedule_facebook_status" => "schedule#schedule_facebook_status_update", :via => [:put,:post]
  match "schedule/get_meetup_venues" => "schedule#get_group_venues", :as=> :get_meetup_venues
  match "schedule/get_meetup_events" => "schedule#get_group_events", :as=> :get_meetup_events
  match "services" => "oauth_consumers#index", :as=> :services

  devise_for :users
  root :to => 'dashboard#index'

end

app/controllers/oauth_consumers_controller.rb
require 'oauth/controllers/consumer_controller'
class OauthConsumersController < ApplicationController
  include Oauth::Controllers::ConsumerController
  # Replace this with the equivalent for your authentication framework
  # Eg. for devise
  #
  #   before_filter :authenticate_user!, :only=>:index
  #before_filter :login_required, :only=>:index
  before_filter :authenticate_user!

  def index
    @consumer_tokens=ConsumerToken.all :conditions=>{:user_id=>current_user.id}
    @services=OAUTH_CREDENTIALS.keys-@consumer_tokens.collect{|c| c.class.service_name}
  end

  def callback
  	super
  end

  def client
    super
  end


  protected

  # Change this to decide where you want to redirect user to after callback is finished.
  # params[:id] holds the service name so you could use this to redirect to various parts
  # of your application depending on what service you're connecting to.
  def go_back
    redirect_to root_url
  end

  # The plugin requires logged_in? to return true or false if the user is logged in. Uncomment and
  # call your auth frameworks equivalent below if different. eg. for devise:
  #
   def logged_in?
     user_signed_in?
   end

  # The plugin requires current_user to return the current logged in user. Uncomment and
  # call your auth frameworks equivalent below if different.
  # def current_user
  #   current_person
  # end

  # The plugin requires a way to log a user in. Call your auth frameworks equivalent below
  # if different. eg. for devise:
  #
  # def current_user=(user)
  #   sign_in(user)
  # end

  # Override this to deny the user or redirect to a login screen depending on your framework and app
  # if different. eg. for devise:
  #
  # def deny_access!
  #   raise Acl9::AccessDenied
  # end
end

app/views/oauth_consumers/index.html.erb
<%= render "layouts/navigation" %>
<h1>Services</h1>

<% if @consumer_tokens.empty? %>
  <p>
    You are currently not connected to any external services.
  </p>
<% else %>
  <p>
    You are connected to the following services:
  </p>
  <ul>
    <% @consumer_tokens.each do |token| %>
      <li>
        <%= link_to token.class.service_name.to_s.humanize, oauth_consumer_path(token.class.service_name) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% unless @services.empty? %>
<h3>You can connect to the following services:</h3>
<ul>
  <% @services.each do |service| %>
    <li>
      <%= link_to service.to_s.humanize, oauth_consumer_path(service) %>
    </li>
  <% end %>
</ul>
<% end %>

app/views/oauth_consumers/show.html.erb
<h1>You are already Connected to <%=params[:id].humanize%></h1>
<% form_tag oauth_consumer_path(params[:id]),:method=>:delete do %>
  <%=submit_tag "Disconnect" %>
  or
  <%=submit_tag "Reconnect" %>
  if you experienced a problem.
<% end %>